### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: an illegal memory access was encountered

### ISSUE THREAD

**Issue by zhangxiann** [pyg-team/pytorch_geometric#1262]
When I`am training, the model works fine. But when I start testing, this error occurs. Why?
```
epoch: 1 loss: 3.392380952835083 train_batch_acc: 0.0625
epoch: 1 loss: 2.941084146499634 train_batch_acc: 0.15625
epoch: 1 loss: 2.138481616973877 train_batch_acc: 0.34375
epoch: 1 loss: 1.3853774070739746 train_batch_acc: 0.59375
epoch: 1 loss: 1.3555893898010254 train_batch_acc: 0.65625
epoch: 1 loss: 0.9268301725387573 train_batch_acc: 0.75
epoch: 1 loss: 0.8250795006752014 train_batch_acc: 0.6875
train acc is 0.436500
epoch: 1 test_batch_acc: 0.03125
Traceback (most recent call last):
  File "train_3d_graph_gait.py", line 174, in <module>
    test_acc = test(test_loader)
  File "train_3d_graph_gait.py", line 134, in test
    end_point = model(data)
  File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "train_3d_graph_gait.py", line 82, in forward
    x = max_pool_x(cluster, data.x, data.batch, size=1)
  File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/torch_geometric/nn/pool/max_pool.py", line 33, in max_pool_x
    return _max_pool_x(cluster, x, (batch.max().item() + 1) * size)
  File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/torch_geometric/nn/pool/max_pool.py", line 9, in _max_pool_x
    return scatter_('max', x, cluster, dim=0, dim_size=size)
  File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/torch_geometric/utils/scatter.py", line 39, in scatter_
    out[out == fill_value] = 0
RuntimeError: copy_if failed to synchronize: an illegal memory access was encountered
```

**Comment by rusty1s** [comment]
Seems like not all data is on the same device. Can you check that?

**Comment by xiechuanyu** [comment]
I add `print(data.batch.device)` in each iteration of the DataLoader, include `train` and `test`. Is this code enough?
```
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
epoch: 1 loss: 1.2242294549942017 train_batch_acc: 0.65625
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
cuda:1
epoch: 1 loss: 1.1242997646331787 train_batch_acc: 0.65625
cuda:1
cuda:1
train acc is 0.403000
cuda:1
epoch: 1 test_batch_acc: 0.03125
cuda:1
cuda:1
cuda:1
cuda:1
Traceback (most recent call last):
  File "train_3d_graph_gait.py", line 183, in <module>
    test_acc = test(test_loader)
  File "train_3d_graph_gait.py", line 136, in test
    end_point = model(data)
  File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "train_3d_graph_gait.py", line 82, in forward
    x = max_pool_x(cluster, data.x, data.batch, size=1)
  File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/torch_geometric/nn/pool/max_pool.py", line 33, in max_pool_x
    return _max_pool_x(cluster, x, (batch.max().item() + 1) * size)
  File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/torch_geometric/nn/pool/max_pool.py", line 9, in _max_pool_x
    return scatter_('max', x, cluster, dim=0, dim_size=size)
  File "/home/anaconda/envs/graph-wyx/lib/python3.6/site-packages/torch_geometric/utils/scatter.py", line 39, in scatter_
    out[out == fill_value] = 0
RuntimeError: copy_if failed to synchronize: an illegal memory access was encountered
```

**Comment by xiechuanyu** [comment]
This erroe is weird because it **only occurs at testing time**. I have thought that there is something wrong with my test data, then I set Both path of the **training Dataset** and **testing Dataset** as my training data directory, so that the testing data is the same as training data.  But this error still happens in testing time.

**Comment by rusty1s** [comment]
Can you run the test code on CPU to get a more reasonable error message?

**Comment by xiechuanyu** [comment]
When I run the test code on CPU, the error message only few words..
```
corrupted size vs. prev_size
Aborted (core dumped)
```

**Comment by xiechuanyu** [comment]
sometimes it occurs at the first epoch, sometimes it happens after several epochs.

**Comment by xiechuanyu** [comment]
I add `CUDA_LAUNCH_BLOCKING=1` before running the script, some new message appears.
```
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/THCTensorMathCompare.cuh:82
```

**Comment by rusty1s** [comment]
Can you show me an example to reproduce this? I feel like it might be an issue with batching with graphs that contain isolated nodes/no nodes at all.

**Comment by laihaoran** [comment]
Do you have finished it, I have the same problem like you.

**Comment by laihaoran** [comment]
I find that it's because my edgs index was out of the number of node. I create the edgs index by matlab, which index is created from 1.

**Comment by xiechuanyu** [comment]
> I find that it's because my edgs index was out of the number of node. I create the edgs index by matlab, which index is created from 1.

thanks for your comment, I will check my code

**Comment by xiechuanyu** [comment]
I have solved this problem.
It was because I add data augmentation `T.RandomScale([0.96, 0.999])` on the training dataset without add it to testing dataset.
After removing this `RandomScale`, the error has gone.

**Comment by netphantom** [comment]
Hi there, I am also issuing this problem with the DNA network.

```
Traceback (most recent call last):
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/bin/graphnn", line 33, in <module>
    sys.exit(load_entry_point('graphnn==3.1.0.dev0', 'console_scripts', 'graphnn')())
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/graphnn-3.1.0.dev0-py3.8.egg/graphnn/cli.py", line 72, in main
    parser.dispatch()
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/graphnn-3.1.0.dev0-py3.8.egg/graphnn/clinterpreter/dna.py", line 34, in dna_train
    Trainer("dna", args)
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/graphnn-3.1.0.dev0-py3.8.egg/graphnn/py_geom/trainers.py", line 91, in __init__
    self.__train_model()
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/graphnn-3.1.0.dev0-py3.8.egg/graphnn/py_geom/trainers.py", line 117, in __train_model
    out = self.model(x=self.data.x, edge_index=self.data.edge_index)
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/graphnn-3.1.0.dev0-py3.8.egg/graphnn/py_geom/structures.py", line 301, in forward
    x = layer(x_all, edge_index)
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/torch_geometric/nn/conv/dna_conv.py", line 268, in forward
    edge_index, edge_weight = gcn_norm(  # yapf: disable
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 56, in gcn_norm
    edge_index, tmp_edge_weight = add_remaining_self_loops(
  File "/export/homes/home/net_phantom/miniconda3/envs/graphnn/lib/python3.8/site-packages/torch_geometric/utils/loop.py", line 125, in add_remaining_self_loops
    edge_index = torch.cat([edge_index[:, mask], loop_index], dim=1)
RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```
The code that generated the error is this:

```
class DnaNet(torch.nn.Module, ABC):
    def __init__(self, dataset: Data, classes: int, heads: int, hidden_channels: int, dropout: float, layers: int,
                 groups: int):
        super(DnaNet, self).__init__()
        self.hidden_channels = hidden_channels
        self.hidden_channels = hidden_channels
        self.lin1 = torch.nn.Linear(dataset.num_node_features, hidden_channels)

        self.layers = torch.nn.ModuleList()
        for _ in range(layers):
            self.layers.append(DNAConv(hidden_channels, heads, groups, dropout=dropout, cached=True))

        self.lin2 = torch.nn.Linear(hidden_channels, classes)
        self.dropout = dropout

    def forward(self, x, edge_index):
        x = F.relu(self.lin1(x))
        x = F.dropout(x, self.dropout)
        x_all = x.view(-1, 1, self.hidden_channels)

        for layer in self.layers:
            x = layer(x_all, edge_index)
            x = F.relu(x)
            x = x.view(-1, 1, self.hidden_channels)
            x_all = torch.cat([x_all, x], dim=1)
        x = x_all[:, -1]
        x = F.dropout(x, self.dropout)
        x = self.lin2(x)

        return torch.sigmoid(x)
```

with: classes = 2,  
layers: 3
hidden_channels: 100
groups: 1
head: 2

I'm using a nvidia Titan X

Using the CPU, it works perfectly

**Comment by rusty1s** [comment]
Are you using a custom dataset? Does your code run on a dataset provided by PyG, *e.g.*, `Planetoid`?

**Comment by netphantom** [comment]
Yes I'm using a custom dataset, and Yes, it works on the example provided for DNA (Planetoid)

**Comment by netphantom** [comment]
Debugging the code, I found that, when I perform `x = self.lin1(x)`I get this error: `{RuntimeError}cuda runtime error (700) : an illegal memory access was encountered at /pytorch/aten/src/THC/THCCachingHostAllocator.cpp:278` and the value of `edge_index`is somehow "lost"

**Comment by netphantom** [comment]
My fault. I forgot to move the model to CUDA.

**Comment by leaf918** [comment]
@rusty1s can you help me to check what is this problem?

this error occured in training process,that happened after 1850 iters.

2023-02-10 03:29:09,177 [INFO] Epoch: 0, Step: 1830/4995, Avg Loss: 0.6258, Avg Regression Loss 0.0623
, Avg Classification Loss: 0.5635
2023-02-10 03:29:18,352 [INFO] Epoch: 0, Step: 1840/4995, Avg Loss: 0.5678, Avg Regression Loss 0.0606
, Avg Classification Loss: 0.5072
2023-02-10 03:29:27,417 [INFO] Epoch: 0, Step: 1850/4995, Avg Loss: 0.6005, Avg Regression Loss 0.0684
, Avg Classification Loss: 0.5320
Traceback (most recent call last):
  File "train_ssd_data_aug_220623.py", line 451, in <module>
    device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "train_ssd_data_aug_220623.py", line 153, in train
    regression_loss, classification_loss = criterion(confidence, locations, labels, boxes)
  File "/root/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, 
in __call__
    result = self.forward(*input, **kwargs)
  File "/root/host_dir/rd_car_LPD_from_jetsoninference/detection/ssd/vision/nn/multibox_loss.py", line
 41, in forward
    classification_loss = F.cross_entropy(confidence.reshape(-1, num_classes), labels[mask], size_aver
age=False)
RuntimeError: copy_if failed to synchronize: an illegal memory access was encountered

**Comment by rusty1s** [comment]
Can you confirm that `labels.max() < num_classes`?
