### ISSUE TITLE
RuntimeError: cuda runtime error (6) 

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [pyg-team/pytorch_geometric#329]
## 🐛 Bug
Hi,

it's me again with a new bug :) So I am trying to train DGCNN on ModelNet10

```

#imports

pre_transform = T.NormalizeScale()

train_ds = ModelNet(root='./',
             train=True,
             pre_transform=pre_transform)

test_ds = ModelNet(root='./',
             train=True,
             pre_transform=pre_transform)


device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

train_dl = DataLoader(train_ds, batch_size=16)

test_dl = DataLoader(test_ds, batch_size=16)

class DynamicEdgeConv(gnn.EdgeConv):
    def __init__(self, k=6, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.k = k

    def forward(self, pos, batch):
        edge_index = knn_graph(pos, self.k, batch, loop=False)
        return super().forward(pos, edge_index)


model = ... # here I use DynamicEdgeConv

model = DGCNNClassification(3,10).to(device)

optimizer = Adam(model.parameters(), 0.001)
criterion = nn.CrossEntropyLoss()

for data in train_dl:
    start = time.time()
    optimizer.zero_grad()
    data = data.to(device)
    print(data)
    out = model(data.pos, data.batch) #HERE BOOM
    loss = criterion(out, data.y)
    loss.backward()
    print('[INFO] loss={} elapsed={:.2f}'.format(loss.item(), time.time() - start))
    optimizer.step()

```
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCReduceAll.cuh line=327 error=6 : the launch timed out and was terminated
Traceback (most recent call last):
  File "DGCNN.py", line 144, in <module>
    out = model(data.pos, data.batch)
  File "/home/fzuppic/anaconda3/envs/gdl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "DGCNN.py", line 115, in forward
    out = conv(out, batch)
  File "/home/fzuppic/anaconda3/envs/gdl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "DGCNN.py", line 68, in forward
    edge_index = knn_graph(pos, self.k, batch, loop=False)
  File "/home/fzuppic/anaconda3/envs/gdl/lib/python3.7/site-packages/torch_cluster/knn.py", line 109, in knn_graph
    edge_index = knn(x, x, k if loop else k + 1, batch, batch)
  File "/home/fzuppic/anaconda3/envs/gdl/lib/python3.7/site-packages/torch_cluster/knn.py", line 57, in knn
    return torch_cluster.knn_cuda.knn(x, y, k, batch_x, batch_y)
RuntimeError: cuda runtime error (6) : the launch timed out and was terminated at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCReduceAll.cuh:327
```
It seems that `torch_cluster` has some problem with CUDA.

## Environment

* OS:
* Python version: 3.7
* PyTorch version: 1.1
* CUDA/cuDNN version: 10
* GCC version:
* Any other relevant information:

Thank you a lot,

Francesco

**Comment by rusty1s** [comment]
Runs fine for me. Can you do me a favor and run the `torch_cluster` test suite?

**Comment by FrancescoSaverioZuppichini** [comment]
Okay, tests are gree

```
----------- coverage: platform linux, python 3.7.3-final-0 -----------
Name                        Stmts   Miss  Cover
-----------------------------------------------
torch_cluster/__init__.py       9      0   100%
torch_cluster/fps.py           10      0   100%
torch_cluster/graclus.py       10      0   100%
torch_cluster/grid.py           9      0   100%
torch_cluster/knn.py           36      0   100%
torch_cluster/nearest.py       21      0   100%
torch_cluster/radius.py        32      0   100%
torch_cluster/rw.py             3      0   100%
-----------------------------------------------
TOTAL                         130      0   100%


================== 109 passed in 4.09 seconds ===================
```
Probably the error is related to the GPUs, I will contact the guy in charge of them.

Thank you again :)

**Comment by GrumpyZhou** [comment]
@FrancescoSaverioZuppichini  Hi i have just implemented DGCNN for classification as well and the same environment with yours. So for me it was not a directly an error, i just noticed it is super slow at the beginning. The problem comes from knn_graph, since some point samples might contain a lot of points, then the function becomes slow which is actually expected. 

My solution is just add SamplePoint(1024) in preprocessing step, may be it also help you.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @GrumpyZhou, 

Thank you but I actually end up doing the same and now it works perfectly. Do you also sample on the test set? 

By sampling 1024 * 4 in the test set, I have 92.5% accuracy (that is super good actually). I trained for 40 epochs with Adam and by reducing the lr by a factor of 0.2 every 10. I also remove the first big 1024 layer and I did not use the spatial transform so I don't know, the result seems to good to be true.

Cheers :)

**Comment by GrumpyZhou** [comment]
@FrancescoSaverioZuppichini  

Yes, but i only  sampled 1024 points in test set and i got similar accuracy 91.17% on modelnet40. 

:)

**Comment by GrumpyZhou** [comment]
Hi @rusty1s ,

Thanks for the great work! I am wondering do you think i should make a pull request since i want to contribute as well. 
I have re-implemented [Dynamic Graph Convolution network](https://arxiv.org/abs/1801.07829) for both classification and segmentation. The results seems super good to me :) 
Though i am not sure i should say it here or open another issue ...

**Comment by rusty1s** [comment]
Awesome! Would really like you to see contributing. Just send a PR :)

**Comment by FrancescoSaverioZuppichini** [comment]
@GrumpyZhou Then I am wondering why I got 92.5% accuracy. Can you share your code? Mine is at https://github.com/FrancescoSaverioZuppichini/GDL-project/blob/master/DGCNN.ipynb

I remove the big 1024 layer to speed up training and also I  haven't the spatial transform but Professor Bronstein told me that they remove it in the new version that should be published soon

**Comment by GrumpyZhou** [comment]
Hi @FrancescoSaverioZuppichini,

I have just uploaded my implementation to examples.  I am not sure why yours is better, but i didn't do any hyper-parameter search and only used the numbers in the original paper.

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @GrumpyZhou. Thank you for the script. I also did not do any hyper-parameter search, I did not use Dropout (since it should not be used with batchnorm) and I have always scored more than $92%$ on the test set. I don't know what to say :)

**Comment by jeannotes** [comment]
> @GrumpyZhou Then I am wondering why I got 92.5% accuracy. Can you share your code? Mine is at https://github.com/FrancescoSaverioZuppichini/GDL-project/blob/master/DGCNN.ipynb
> 
> I remove the big 1024 layer to speed up training and also I haven't the spatial transform but Professor Bronstein told me that they remove it in the new version that should be published soon

is  that  paper published? @FrancescoSaverioZuppichini 

by the way, @GrumpyZhou , I have try your dgcnn-segmentation implementions, the ious are far too good, all exceeds 94%, is there anything wrong, I notice that when I only train one category, the point cloud seg label not starts with 0,eg, 'Cap', it has 7 classes, you may check it out

**Comment by GrumpyZhou** [comment]
@jeannotes   I am not sure I get your question correctly. What do you mean by 'Cap' has 7 classes? I think 'Cap' has only two classes and the corresponding class ids are 6 and 7, and class id 0 belongs to Airplane. The class ids are defined in [shapenet.py ](https://github.com/rusty1s/pytorch_geometric/blob/22bef0517cbaf51b14428fddb2be4a49dd924609/torch_geometric/datasets/shapenet.py#L13), can you also check whether this solves your question?

**Comment by FrancescoSaverioZuppichini** [comment]
> > @GrumpyZhou Then I am wondering why I got 92.5% accuracy. Can you share your code? Mine is at https://github.com/FrancescoSaverioZuppichini/GDL-project/blob/master/DGCNN.ipynb
> > I remove the big 1024 layer to speed up training and also I haven't the spatial transform but Professor Bronstein told me that they remove it in the new version that should be published soon
> 
> is that paper published? @FrancescoSaverioZuppichini
> 
> by the way, @GrumpyZhou , I have try your dgcnn-segmentation implementions, the ious are far too good, all exceeds 94%, is there anything wrong, I notice that when I only train one category, the point cloud seg label not starts with 0,eg, 'Cap', it has 7 classes, you may check it out

I have no idea mate :)
