### ISSUE TITLE
NeighborLoader with loader worker processes fails on GPU

### ISSUE THREAD

**Issue by SebastianHurubaru** [pyg-team/pytorch_geometric#5340]
### 🐛 Describe the bug

When using NeighborLoader with multi-process data loading on GPU, we get the following error:
```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

Running on CPU works fine. The deprecated `NeighborSampler` seems to work fine on all devices!

Here is the **IPython (Jupyter notebook) code** used to reproduce the error for `NeighborLoader`. The latter part contains cells showing that `NeighborSampler` works fine:

```
import torch
import os
print("PyTorch has version {}".format(torch.__version__))

# Install torch geometric
!pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.12.1+cu113.html
!pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.12.1+cu113.html
!pip install torch-geometric

## Setup

import os
import copy
import torch
import pandas as pd
import torch.nn.functional as F
import torch_geometric.transforms as T

from torch_geometric.nn import SAGEConv
from torch_geometric.loader import NeighborLoader, NeighborSampler

# Install OGB
!pip install -q ogb

from ogb.nodeproppred import PygNodePropPredDataset, Evaluator

dataset_name = 'ogbn-arxiv'
dataset = PygNodePropPredDataset(name=dataset_name,
                                transform=T.ToSparseTensor())
data = dataset[0]
data.adj_t = data.adj_t.to_symmetric()
device = 'cuda' if torch.cuda.is_available() else 'cpu'

print('Device: {}'.format(device))

data = data.to(device)

split_idx = dataset.get_idx_split()
train_idx = split_idx['train'].to(device)

## NeighborLoader section


subgraph_batch_loader = NeighborLoader(data, input_nodes=train_idx,
                                num_neighbors=[-1], batch_size=4096,
                                shuffle=True, num_workers=2)

for batched_data in subgraph_batch_loader:
  print(f'batched_data.batch_size: {batched_data.batch_size}')

## NeighborSampler section


subgraph_batch_sampler = NeighborSampler(data.adj_t, node_idx=train_idx,
                                sizes=[-1], batch_size=4096,
                                shuffle=True, num_workers=2)

for batch_size, n_id, adjs in subgraph_batch_sampler:
  print(f'batch_size: {batch_size}')
```

### Environment

* PyG version: 2.1.0.post1
* PyTorch version:1.12.1
* OS: Ubuntu 18.04.6 LTS
* Python version:3.7.13
* CUDA/cuDNN version: cu113
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): Used the Google Colab environment

**Comment by rusty1s** [comment]
Any PyTorch `DataLoader` working on CUDA tensors needs to operate in the main process (i.e., `num_workers=0`). This is a current limitation of CUDA. Nothing we can do about this for now. Notably though, it is possible (and will in major speed-ups) to only send node features to the GPU (for fast feature fetching access), but leaving `edge_index` tensors on CPU - an example of this is shown [here](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/reddit.py#L17).

The old `NeighborSampler` will map CUDA tensors to CPU first - that's why this issue isn't spotted there at all.

**Comment by SebastianHurubaru** [comment]
@rusty1s used the approach you mentioned and it looks great now! Thanks for your fast reply!

**Comment by LukeLIN-web** [comment]
@rusty1s  
When I try  pytorch_geometric/training_benchmark.py 
I also meet this problem :
```
Dataset: ogbn-mag
Configuration of ogbn-mag + edge_cnn not supported. Skipping.
Configuration of ogbn-mag + gat not supported. Skipping.
Configuration of ogbn-mag + gcn not supported. Skipping.
Configuration of ogbn-mag + pna not supported. Skipping.
Training bench for rgat:
----------------------------------------------
Batch size=512, Layers amount=2, Num_neighbors=[10, 10], Hidden features size=64, Sparse tensor=False
RuntimeError: CUDA error: initialization error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
Environment
PyG version: 2.1.0.post1
PyTorch version:1.10.0
OS: Ubuntu 18.04.6 LTS
Python version:3.7.11
CUDA/cuDNN version: cu113

**Comment by rusty1s** [comment]
Thanks for reporting. I fixed it in #6070.
