### ISSUE TITLE
CUDA error: device-side assert triggered while `RandomLinkSplit()`ing data

### ISSUE THREAD

**Issue by Newiz430** [pyg-team/pytorch_geometric#5721]
### 🐛 Describe the bug

I'm encountering a CUDA error with `RandomLinkSplit()` on PubMed and some Non-Planetoid datasets like Amazon-Photo and WikiCS:
~~~python
import torch_geometric.transforms as T

dataset = get_dataset(path, args.dataset) # returns `torch_geometric.datasets.SomeDataset()`
data = dataset[0]
...
# splitting data
split = T.RandomLinkSplit(num_val=0., num_test=0., is_undirected=True, add_negative_train_samples=False)
train_data = split(data)[0] # line 122
~~~
When I run my training code on CUDA, assertion errors like "index out of bounds" occur:
~~~
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [465,0,0], thread: [36,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [465,0,0], thread: [37,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [465,0,0], thread: [38,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [465,0,0], thread: [39,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [465,0,0], thread: [40,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [465,0,0], thread: [41,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [465,0,0], thread: [42,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [16,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [17,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [18,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [65,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [66,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [67,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [68,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [69,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [71,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [72,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [73,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [74,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [57,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [58,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [59,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [103,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [104,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [105,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [106,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [107,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [108,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [109,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [110,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [111,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [112,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [113,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [114,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [464,0,0], thread: [115,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [123,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [124,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [125,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [126,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [232,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File ".../train.py", line 318, in <module>
    res = test(epoch)
  File ".../train.py", line 122, in test
    train_data = split(data)[0]
File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/transforms/random_link_split.py", line 116, in __call__
  add_self_loops(data.edge_index)[0], num_nodes=data.num_nodes,
File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/utils/loop.py", line 82, in add_self_loops
  N = maybe_num_nodes(edge_index, num_nodes)
File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/utils/num_nodes.py", line 25, in maybe_num_nodes
  return int(edge_index.max()) + 1 if edge_index.numel() > 0 else 0
RuntimeError: CUDA error: device-side assert triggered
~~~
This is weird for me cause no errors pumping out and code proceeds successfully when I set `device='cpu'`, or use Cora / Citeseer on CUDA.
I've pip-upgraded PyG to 2.1.0.post1 and the issue still exists, but at `negative_sampling.py` this time:
~~~
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [100,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [100,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [100,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [100,0,0], thread: [3,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
......
/opt/conda/conda-bld/pytorch_1616554793803/work/aten/src/ATen/native/cuda/IndexKernel.cu:142: operator(): block: [44,0,0], thread: [63,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/dhc/new_ch/GCA/train.py", line 318, in <module>
    res = test(epoch)
  File "/home/dhc/new_ch/GCA/train.py", line 122, in test
    train_data = split(data)[0]
  File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/transforms/random_link_split.py", line 207, in __call__
    neg_edge_index = negative_sampling(edge_index, size,
  File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/utils/negative_sampling.py", line 50, in negative_sampling
    idx, population = edge_index_to_vector(edge_index, size, bipartite,
  File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/utils/negative_sampling.py", line 277, in edge_index_to_vector
    row, col = row[mask], col[mask]
RuntimeError: CUDA error: device-side assert triggered
~~~
I'd appreciate a solution available for PyG==2.0.1. Huge thanks to anyone helping :hearts:

### Environment

* PyG version: 2.0.1, 2.1.0.post1 (I've tried on both versions)
* PyTorch version: 1.8.1
* OS: Ubuntu 16.04.7 LTS
* Python version: 3.8
* CUDA/cuDNN version: 11.1
* How you installed PyTorch and PyG (`conda`, `pip`, source): `pip`

**Comment by wwymak** [comment]
Not sure if it helps -- but if I run your example on colab with pytorch ==1.12.1+cu113 and pyG==2.1.0 there is no CUDA error

**Comment by Newiz430** [comment]
I wonder if there is a substitute for `RandomLinkSplit()` cuz I only need a `torch_geometric.data.Data` object with negative sampled properties `edge_label` and `edge_label_index`.
It seems that the `Data` object returned from `RandomLinkSplit()` is different from other `Data` objects: 
~~~python
>>> data
Data(x=[7650, 745], edge_index=[2, 238162], y=[7650])
>>> data.edge_label
Traceback (most recent call last):
  File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/data/data.py", line 345, in __getattr__
    return getattr(self._store, key)
  File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/data/storage.py", line 50, in __getattr__
    raise AttributeError(
AttributeError: 'GlobalStorage' object has no attribute 'edge_label'
>>> split = T.RandomLinkSplit(num_val=0., num_test=0., is_undirected=True, add_negative_train_samples=False)
>>> train_data = split(data)[0]
>>> train_data # 2 new properties `edge_label` and `edge_label_index` can be seen
Data(x=[7650, 256], edge_index=[2, 238162], y=[7650], edge_label=[364893], edge_label_index=[2, 364893])
>>> train_data.edge_label
tensor([1., 1., 1.,  ..., 0., 0., 0.])
~~~
Does the difference derive from some implicit negative sampling process in `RandomLinkSplit.__call__()` (even if I set `add_negative_train_samples=False`)?

**Comment by rusty1s** [comment]
```python
import torch_geometric.transforms as T
from torch_geometric.datasets import Planetoid

dataset = Planetoid('/tmp/Planetoid', name='PubMed')
data = dataset[0].cuda()

split = T.RandomLinkSplit(num_val=0., num_test=0., is_undirected=True,
                          add_negative_train_samples=False)
train_data = split(data)[0]
print(train_data)
```
works for me. Can you confirm?

It also prints out
```python
print(train_data.edge_label)
>>> tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0')
```

**Comment by Newiz430** [comment]
@rusty1s I ran your code snippet and sadly it crashed again with the same errors. Sometimes it looked like this:
~~~
Traceback (most recent call last):
  File "/home/dhc/new_ch/GCA/lp.py", line 35, in <module>
    train_data = split(data)[0]
  File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/transforms/random_link_split.py", line 85, in __call__
    perm = perm[data.edge_index[0] <= data.edge_index[1]]
RuntimeError: invalid shape dimension -467690788
~~~
or:
~~~
  File "/home/dhc/new_ch/GCA/lp.py", line 35, in <module>
    train_data = split(data)[0]
  File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/transforms/random_link_split.py", line 95, in __call__
    raise ValueError("Insufficient number of edges for training.")
ValueError: Insufficient number of edges for training.
~~~
I had to step into `RandomLinkSplit.__call__()` in debugging mode of PyCharm, where I found something beyond expectation. 
Lines 83~85 in `torch_geometric/transforms/random_link_split.py`:
~~~python
perm = torch.randperm(data.num_edges, device=data.edge_index.device)
if self.is_undirected:
    perm = perm[data.edge_index[0] <= data.edge_index[1]]
~~~
`perm[data.edge_index[0] <= data.edge_index[1]]` unexpectedly gives an empty tensor which lead to ValueError #2 (here WikiCS is used).
![image](https://user-images.githubusercontent.com/75777601/196438789-a6ac6962-63a2-45bf-ab37-3edc47e0a7b5.png)
![20221018212847](https://user-images.githubusercontent.com/75777601/196443296-38f90bfd-bcf4-4257-a34e-f01dd99a23fd.png)

If I run lines 83~85 in console, here comes the weirdest thing:

**Comment by Newiz430** [comment]
@rusty1s I ran your code snippet and sadly it crashed again with the same errors. Sometimes it looked like this:
~~~
Traceback (most recent call last):
  File "/home/dhc/new_ch/GCA/lp.py", line 35, in <module>
    train_data = split(data)[0]
  File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/transforms/random_link_split.py", line 85, in __call__
    perm = perm[data.edge_index[0] <= data.edge_index[1]]
RuntimeError: invalid shape dimension -467690788
~~~
or:
~~~
  File "/home/dhc/new_ch/GCA/lp.py", line 35, in <module>
    train_data = split(data)[0]
  File "/home/dhc/anaconda3/lib/python3.8/site-packages/torch_geometric/transforms/random_link_split.py", line 95, in __call__
    raise ValueError("Insufficient number of edges for training.")
ValueError: Insufficient number of edges for training.
~~~
I had to step into `RandomLinkSplit.__call__()` in debugging mode of PyCharm, where I found something beyond expectation. 
Lines 83~85 in `torch_geometric/transforms/random_link_split.py`:
~~~python
perm = torch.randperm(data.num_edges, device=data.edge_index.device)
if self.is_undirected:
    perm = perm[data.edge_index[0] <= data.edge_index[1]]
~~~
`perm[data.edge_index[0] <= data.edge_index[1]]` unexpectedly gives an empty tensor which lead to ValueError(2) (here WikiCS is used).
![image](https://user-images.githubusercontent.com/75777601/196438789-a6ac6962-63a2-45bf-ab37-3edc47e0a7b5.png)
![20221018212847](https://user-images.githubusercontent.com/75777601/196443296-38f90bfd-bcf4-4257-a34e-f01dd99a23fd.png)

If I run lines 83~85 in console, here comes the weirdest thing: 
![20221018212417](https://user-images.githubusercontent.com/75777601/196444505-c3ec3280-0c68-4b1a-b5d4-26a8a5d53ebd.png)
and the initial assertion errors will reappear if I execute `perm[data.edge_index[0] <= data.edge_index[1]]` in console by several times. 

I can definitely say this is a bug related to CUDA. I'll try the code on another device later.

**Comment by Newiz430** [comment]
Same errors occurred on PubMed and Amazon-Photo, too.

**Comment by rusty1s** [comment]
Mh, really weird. There seems to be something off with the CUDA implementation for you.

Is it possible to debug for you what is happening under the hood? For example, what does
```python
print(perm.shape)
print(perm)
print(data.edge_index[0].min(), data.edge_index[0].max())
print(data.edge_index[1].min(), data.edge_index[1].max())
```
report for you right before the
```python
perm = perm[data.edge_index[0] <= data.edge_index[1]]
```
call?

**Comment by Newiz430** [comment]
For PubMed: 
![20221019202928](https://user-images.githubusercontent.com/75777601/196691077-f24b1196-6855-4727-bdc4-2507d299312d.png)
For Amazon-Photo:
![20221019203301](https://user-images.githubusercontent.com/75777601/196691832-01340196-fb74-48cc-95eb-eaa004c880ca.png)

Strangely, errors disappeared for the first few epochs and then reappeared when I was debugging on Amazon-Photo: 
![20221019204000](https://user-images.githubusercontent.com/75777601/196693287-5a990926-2a4c-451e-a919-e9eb7a6e38d5.png)
Huge volatility of these bugs makes them kinda hard to reproduce.

**Comment by Newiz430** [comment]
Yep it still remains with `device=cuda:1` or other CUDA devices.

**Comment by EdisonLeeeee** [comment]
Why does perm become so large in Pubmed? Can you figure it out?
![image](https://user-images.githubusercontent.com/39986668/196703022-9aab28e1-6725-4890-8103-522490940510.png)

**Comment by Newiz430** [comment]
@EdisonLeeeee Yea I've noticed the anomaly of `torch.randperm()`. Sometimes when input size is greater than around 30,000, some entries explode like this. And sometimes it failed to randomise entries: 
![image](https://user-images.githubusercontent.com/75777601/196705435-d61d67c1-c87e-43c2-a40d-fab129371b81.png)

**Comment by EdisonLeeeee** [comment]
Could you simply try `torch.randperm(1000000, device=torch.device('cuda:3'))` multiple times to see if it works functionally? I still think the problem comes from your CUDA, either the device or the driver.

**Comment by EdisonLeeeee** [comment]
Even `print(torch.randperm(1000000), device=torch.device('cuda:3'))`? That's weird. Perhaps you need to try it on other GPUs or OS.

**Comment by Newiz430** [comment]
Thank god the errors disappeared on my Windows PC CUDA=11.7 with the newest versions of PyTorch and PyG. 
It turns out the problem is somehow specific to the GPU or OS I previously used. Still wondering why these errors occured but what more can I do lol
My sincere gratitude to @EdisonLeeeee, @wwymak and the Creator @rusty1s for answering this issue :heart:
