### ISSUE TITLE
torch sparse CUDA error

### ISSUE THREAD

**Issue by yecohn** [pyg-team/pytorch_geometric#6017]
### 🐛 Describe the bug

Hi everyone,

I installed torch_sparse module, using: 

`conda install pytorch-sparse -c pyg -y
pip install torch-geometric 
`

I am trying to run a simple GCN on a GPU and i am getting this issue: 

> >---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> /tmp/ipykernel_5721/91717404.py in <module>
>      11 
>      12   for epoch in range(1, 1 + args["epochs"]):
> ---> 13     loss = train(model, data, train_idx, optimizer, loss_fn)
>      14     result = test(model, data, split_idx, evaluator)
>      15     train_acc, valid_acc, test_acc = result
> 
> /tmp/ipykernel_5721/2336097427.py in train(model, data, train_idx, optimizer, loss_fn)
>       3     # using the given optimizer and loss_fn.
>       4     model.train()
> ----> 5     input, adj, label = data.x[train_idx], data.adj_t[train_idx],  data.y[train_idx]
>       6     output = model(input, adj)
>       7     loss = loss_fn(output, label)
> 
> ~/anaconda3/envs/drug_torch/lib/python3.8/site-packages/torch_sparse/tensor.py in __getitem__(self, index)
>     583                 dim += 1
>     584             elif item.dtype == torch.long:
> --> 585                 out = out.index_select(dim, item)
>     586                 dim += 1
>     587         elif item == Ellipsis:
> 
> ~/anaconda3/envs/drug_torch/lib/python3.8/site-packages/torch_sparse/index_select.py in <lambda>(self, dim, idx)
>      96 
> ...
> --> 442         return self._op(*args, **kwargs or {})
>     443 
>     444     # TODO: use this to make a __dir__
> 
> RuntimeError: Not compiled with CUDA support

I tried different installation of torch sparse like so: 
```
pip install torch-scatter     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
pip install torch-sparse      -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
pip install torch-cluster     -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-{TORCH}+{CUDA}.html
pip install torch-geometric 
```
but still obtain the same problem.
I am using CUDA 11.7: 

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Wed_Jun__8_16:49:14_PDT_2022
> Cuda compilation tools, release 11.7, V11.7.99
> Build cuda_11.7.r11.7/compiler.31442593_0

and pytorch 1.13.0

Had anyone encontered this issue ? 

Thanks

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment]
You need to run
```
pip install torch-scatter     -f https://pytorch-geometric.com/whl/torch-1.13.0+cu117.html
```
Let me know if this works.

**Comment by yecohn** [comment]
Thanks it works !
