### ISSUE TITLE
RuntimeError: CUDA error: unrecognized error code

### ISSUE THREAD

**Issue by RainYQ** [pyg-team/pytorch_geometric#6276]
### 🐛 Describe the bug

Just call `.cuda()`

```python
batch['3dgraph'] = batch['3dgraph'].cuda()
```

Error output: 
```
  File "/home/--/clean-pvnet/lib/train/trainers/trainer.py", line 93, in train
    batch['3dgraph'] = batch['3dgraph'].cuda()
  File "/home/--/.conda/envs/sepvnet/lib/python3.9/site-packages/torch_geometric/data/data.py", line 230, in cuda
    return self.apply(lambda x: x.cuda(device, non_blocking=non_blocking),
  File "/home/--/.conda/envs/sepvnet/lib/python3.9/site-packages/torch_geometric/data/data.py", line 199, in apply
    store.apply(func, *args)
  File "/home/--/.conda/envs/sepvnet/lib/python3.9/site-packages/torch_geometric/data/storage.py", line 148, in apply
    self[key] = recursive_apply(value, func)
  File "/home/--/.conda/envs/sepvnet/lib/python3.9/site-packages/torch_geometric/data/storage.py", line 498, in recursive_apply
    return func(data)
  File "/home/--/.conda/envs/sepvnet/lib/python3.9/site-packages/torch_geometric/data/data.py", line 230, in <lambda>
    return self.apply(lambda x: x.cuda(device, non_blocking=non_blocking),
RuntimeError: CUDA error: unrecognized error code
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

### Environment

* PyG version: 2.1.0
* PyTorch version: 1.9.0
* OS: centos7
* Python version: 3.9
* CUDA/cuDNN version: 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip 
* Any other relevant information (*e.g.*, version of `torch-scatter`): 
* torch_spline_conv 1.2.1
* torch_scatter 2.0.7
* torch_sparse 0.6.12
* torch_cluster 1.5.9

**Comment by rusty1s** [comment]
This is weird. Can you sahre your `batch` object? Does something like `torch.randn(5).cuda()` work for you?

**Comment by RainYQ** [comment]
`torch.randn(5).cuda()` is ok.
```
>>> torch.randn(5).cuda()
tensor([ 1.2270,  0.1814,  0.5551,  0.6728, -0.9891], device='cuda:0')
```

The `batch` object:
```
    ret = {
           'inp': default_collate([b['inp'] for b in batch]),
           'mask': default_collate([b['mask'] for b in batch]),
           'vertex': default_collate([b['vertex'] for b in batch]),
           'df': default_collate([b['df'] for b in batch]),
           'img_id': default_collate([b['img_id'] for b in batch]),
           '3dgraph': torch_geometric.data.Batch.from_data_list([b['3dgraph'] for b in batch]),
           'meta': default_collate([b['meta'] for b in batch])
    }
```

The batch['3dgraph'] object:
```
torch_geometric.data.Data(x=x, edge_index=edge_index, edge_attr=edge_attr)
```

**Comment by rusty1s** [comment]
Mh, hard to tell. What happens if you run with `CUDA_LAUNCH_BLOCKING=1 ...`? Do other examples on the GPU work for you on PyG?

**Comment by RainYQ** [comment]
with `CUDA_LAUNCH_BLOCKING=1`, I cannot get more information.
I remove all pakages (torch, pyg, etc) and install from conda again, the problem is solved.
