### ISSUE TITLE
SparseTensor doesn't seem to help OutofMemory Error for GMMConv

### ISSUE THREAD

**Issue by romankouz** [pyg-team/pytorch_geometric#6889]
### 🐛 Describe the bug

I have been getting stuck with a Cuda OutofMemoryError for a while on my project. I discovered that the SparseTensor transformation might be helpful. Given that I am using the ```GMMConv``` layer in my project and that the final example of the [SparseTensor API](https://pytorch-geometric.readthedocs.io/en/latest/notes/sparse_tensor.html) uses the GMMConv, I assumed I could apply the same transformation to my data as illustrated below (each gmmlayer is a GMMConv layer).

```
    def forward(self, vals, edges, pseudo):
        for i, gmmlayer in enumerate(self.gmms):
            adj = SparseTensor(row=edges[0], col=edges[1], value=pseudo)
            vals = gmmlayer(vals, adj.t())
            vals = fcl.relu(vals.float())

```

However, replacing the last line in the forward method with ```vals = gmmlayer(vals, edges, pseudo)``` (aka not using SparseTensors at all) results in the exact same MemoryError.

My graph has the following properties (around 1% sparsity in edges):
```DataBatch(x=[5624, 155], edge_index=[2, 332192], y=[5624, 2], pos=[5624, 2], bregma=[1], anid=[1], batch=[5624], ptr=[2])````

The full traceback of the error is here:

```
recation.py:12: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)
/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:441: LightningDeprecationWarning: Setting `Trainer(gpus=[1])` is deprecated in v1.7 and will be removed in v2.0. Please use `Trainer(accelerator='gpu', devices=[1])` instead.
  rank_zero_deprecation(
[2023-03-09 14:33:18,620][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: True (cuda), used: True
[2023-03-09 14:33:18,649][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-03-09 14:33:18,650][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-03-09 14:33:18,650][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-03-09 14:33:18,650][pytorch_lightning.utilities.rank_zero][INFO] - `Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
[2023-03-09 14:33:18,650][pytorch_lightning.utilities.rank_zero][INFO] - `Trainer(limit_val_batches=1.0)` was configured so 100% of the batches will be used..
/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:604: UserWarning: Checkpoint directory /home/roko/spatial/output/lightning_logs/checkpoints/MonetDense exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
[2023-03-09 14:33:19,379][pytorch_lightning.accelerators.cuda][INFO] - LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3,4,5,6,7]
[2023-03-09 14:33:19,381][pytorch_lightning.callbacks.model_summary][INFO] - 
  | Name          | Type                    | Params
----------------------------------------------------------
0 | dense_network | DenseReluGMMConvNetwork | 1.5 M 
----------------------------------------------------------
1.5 M     Trainable params
0         Non-trainable params
1.5 M     Total params
6.060     Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Sanity Checking DataLoader 0:   0%|                                                      | 0/2 [00:00<?, ?it/s]/home/roko/spatial/spatial/models/monet_ae.py:189: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  new_batch_obj.x *= torch.tensor(responses)
DataBatch(x=[5624, 155], edge_index=[2, 332192], y=[5624, 2], pos=[5624, 2], bregma=[1], anid=[1], batch=[5624], ptr=[2])
<class 'torch_sparse.tensor.SparseTensor'>
Error executing job with overrides: ['radius=100']
Traceback (most recent call last):
  File "/home/roko/spatial/spatial/main.py", line 42, in main
    task(cfg)
  File "/home/roko/spatial/spatial/train.py", line 191, in train
    trainer.fit(model, train_loader, val_loader)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit
    call._call_and_handle_interrupt(
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_stage
    self._run_train()
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1190, in _run_train
    self._run_sanity_check()
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1262, in _run_sanity_check
    val_loop.run()
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1480, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/roko/spatial/spatial/models/monet_ae.py", line 237, in validation_step
    _, reconstruction = self(new_batch_obj)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/roko/spatial/spatial/models/monet_ae.py", line 399, in forward
    output = self.dense_network(batch.x, batch.edge_index, pseudo)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/roko/spatial/spatial/models/base_networks.py", line 69, in forward
    vals = gmmlayer(vals, adj.t()) + dense(vals)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/torch_geometric/nn/conv/gmm_conv.py", line 139, in forward
    out = self.propagate(edge_index, x=out, edge_attr=edge_attr,
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/torch_geometric/nn/conv/message_passing.py", line 437, in propagate
    out = self.message(**msg_kwargs)
  File "/home/roko/.cache/pypoetry/virtualenvs/spatial-G_n0JvVf-py3.10/lib/python3.10/site-packages/torch_geometric/nn/conv/gmm_conv.py", line 165, in message
    return (x_j.view(E, K, M) * gaussian.view(E, K, 1)).sum(dim=-2)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.92 GiB (GPU 1; 10.75 GiB total capacity; 4.14 GiB already allocated; 6.35 GiB free; 4.15 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Environment

* PyG version: 2.2.0
* PyTorch version: 1.13.0+cu117
* OS: Linux
* Python version: 3.10.6
* CUDA/cuDNN version: 12.0
* How you installed PyTorch and PyG (`conda`, `pip`, source): whl building (source)
* Any other relevant information (*e.g.*, version of `torch-scatter`): Torch Sparse Version = '0.6.15+pt113cu117'

**Comment by rusty1s** [comment]
I don't think `GMMConv` can leverage the memory-efficient code-path of `SparseTensor`, so you will not see any benefits here. What are the hyperparams of `GMMConv` that you are using?

**Comment by romankouz** [comment]
I believe I am using a kernel size of 25 and a pseudocoordinate dimension of 1.

![image](https://user-images.githubusercontent.com/58533981/224359302-1b203733-544d-4ee4-81ca-81bf388b0818.png)

If it turns out that GMMConv cannot leverage SparseTensor, is a mini-batching of the graphs my next best approach? Thanks again for getting back to me :)

**Comment by rusty1s** [comment]
Mh, I feel 330k edges is not yet something were mini-batching is desperately needed. This might be an issue with how `GMMConv` consumes memory. How much GPU memory do you have? Do you have a small reproducible example?

**Comment by romankouz** [comment]
Unfortunately I don't. However, I looked into the source code and it doesn't seem like GMMConv has a way to work with SparseTensor, so I may have to find a different convolution operation. As for the GPU, we have 11.264 GB per GPU of which we have 8 on our cluster.

**Comment by rusty1s** [comment]
Got it. You are right that `GMMConv` does not currently have a code-path to avoid edge-level representations. If you have the chance to share some example, I am happy to look into it.

**Comment by romankouz** [comment]
Sorry for the delay (I'm very slow). Would something like this suffice?

`import torch
from torch_geometric.data import Data
from torch_geometric.utils import add_random_edge
from torch_geometric.nn import GMMConv

N = 1000

x = torch.tensor([[i] for i in range(N)], dtype=torch.float)

edge_index = torch.tensor([[0],
                           [999]])
for i in range(N-1):
    edge_index, added_edges = add_random_edge(edge_index,p=1/len(edge_index[0]), num_nodes=N)
    
edge_attr = torch.rand((1000,1))

# without SparseTensor
conv = GMMConv(1, 1, dim=1, kernel_size=10)
out = conv(x, edge_index, edge_attr)

from torch_sparse import SparseTensor

# with SparseTensor
adj = SparseTensor(row=edge_index[0], col=edge_index[1], value=edge_attr)
out = conv(x, adj.t())
`

**Comment by rusty1s** [comment]
Yes, this looks all good, but this doesn't run OOM at all, right?

**Comment by romankouz** [comment]
Correct, but perhaps one could easily create a graph that runs OOM by setting N very high since the edge matrix will still get larger and have a dense representation?

**Comment by romankouz** [comment]
I have updated the code to be fully customizable with N

**Comment by rusty1s** [comment]
Ok, will take a look, thanks!
