### ISSUE TITLE
pytorch geometric neighbor loader: CUDA error: ensure indices in 'edge_index' point to valid indices in the interval in your node feature matrix

### ISSUE THREAD

**Issue by jdills26** [pyg-team/pytorch_geometric#7038]
### 🐛 Describe the bug

I'm using PTG's Neighborloader to subset a larger graph to nodes of interest and thier connections (just 1 or 2 hops). [](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/loader/neighbor_loader.html)

```python
n_hops = 1

train_loader = ptg.loader.NeighborLoader(
            data,
            replace = False,
            num_neighbors=[-1] * n_hops, 
            input_nodes=logons_user3106_train, #list of nodes of one type of interest
        )
```

This question is essentially a duplicate of this: [Pytorch Geometric gives me an 'edge_index' error](https://stackoverflow.com/questions/75217346/pytorch-geometric-gives-me-an-edge-index-error)

I am using a pretty simple PTG Autoencoder. I cannot iterate through the data loader. Due to a CUDA error ValueError:
```
Encountered a CUDA error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 26) in your node feature matrix and try again.
```

```python
epochs = 1

model = GAE(GCNEncoder(num_features, out_channels))
model = model.to(device)

for epoch in range(1, epochs + 1):
    for batch in train_loader:
        print(batch.x.shape)
        print(np.unique(batch.edge_index[0]))
        print(np.unique(batch.edge_index[1]))
        print(batch.edge_index[0].max())
        batch_ext = batch.clone()

        batch.to(device)
        loss = train()

        auc, ap = test(batch.edge_index)
        print(' Step loss: {:.4f}, AUC: {:.4f}, AP: {:.4f}'.format(epoch, loss, auc, ap))
        print('\n')
    print('Epoch: {:03d}, , loss: {:.4f}, AUC: {:.4f}, AP: {:.4f}'.format(epoch, loss, auc, ap))
```

If I take the batch the error happened on and look at it, all indices in `batch_ext.edge_index` seem to point to valid indices in my node feature matrix (`batch_ext.x`).

```
Node features size: torch.Size([26, 13])
Unique values in edge index[0]: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Unique values in edge index[1]: [0]
max edge index value: tensor(25)
```

In fact I can take the erroneous batch that I copied to cpu and grab the associated value from either part of the edge index in the node feature matrix without issue:

```python
for i in batch_ext.edge_index[0]:
    print(batch_ext.x[i])

##OR
for i in batch_ext.edge_index[1]:
    print(batch_ext.x[i])
```
returns vectors like:

```
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])
...
```

I can save the bad batch and load it and model it by itself:

```python
batch = torch.load('bad_batch.pkl')
device = torch.device('cuda:0')
out_channels = 2
num_features = batch.num_features
model = GAE(GCNEncoder(num_features, out_channels))
model = model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

batch = batch.to(device)
epochs = 5

for epoch in range(1, epochs + 1):
    loss = train()

    auc, ap = test(batch.edge_index)
    print('Epoch: {:03d}, , loss: {:.4f}, AUC: {:.4f}, AP: {:.4f}'.format(epoch, loss, auc, ap))

#Epoch: 001, , loss: 1.1363, AUC: 0.9668, AP: 0.9599
#Epoch: 002, , loss: 1.0673, AUC: 0.9613, AP: 0.9522
#Epoch: 003, , loss: 1.0160, AUC: 0.9532, AP: 0.9370
#Epoch: 004, , loss: 0.9709, AUC: 0.9737, AP: 0.9730
#Epoch: 005, , loss: 0.9930, AUC: 0.9677, AP: 0.9615
```

**Does anyone have suggestions? Is there any other info I can provide? Thanks so much.** I can't figure out how to debug this any further. I don't see any nulls or inf in my data.

```
ptg.__version__
'2.2.0'

torch.__version__
'1.12.1+cu113'
```

### Environment

* PyG version:
* PyTorch version:
* OS:
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source):
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by LukeLIN-web** [comment]
Neighborloader is usually used on SageConv network.

**Comment by zhiqiangzhongddu** [comment]
Report a similar bug. I got similar errors: "IndexError: Encountered an index error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, X] (got interval [0, Y])" while using NeighborLoader. 

I verified that edge_index.max() is not larger than x.size(0)
`print("layer", layer, x.size(), edge_index.min(), edge_index.max()) 
   
x = layer(x=x, edge_index=edge_index, edge_weight=edge_weight)`

The output I got:
`layer GCNConv(1280, 128) torch.Size([31, 1280]) tensor(0) tensor(30)`

But there is still this index error.

**Comment by zhiqiangzhongddu** [comment]
The error is solved on my side. 
By checking the output, I find when an error happens, the edge_index.max() is always the same as the edge_index.max() of the first batch. So I guess the GCN model remembers the first edge_index it received and does not update it. After setting "cached=False", the error is solved. Hope it is helpful to you.
