### ISSUE TITLE
batch_size makes errors in gcn

### ISSUE THREAD

**Issue by finquick** [pyg-team/pytorch_geometric#7173]
### 🐛 Describe the bug

```
import torch
from torch_geometric.data import Data
from torch_geometric.nn import GCNConv
from torch_geometric.nn import GAE


class GCNEncoder(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super(GCNEncoder, self).__init__()
        self.conv1 = GCNConv(in_channels, 2 * out_channels, cached=True) # cached only for transductive learning
  
    def forward(self, data):
        x = data.x
        edge_index = data.edge_index

        x = self.conv1(x, edge_index).relu()
        return x


if __name__ == "__main__":
    model = GCNEncoder(in_channels=10, out_channels=5).cuda()

    edge_index = torch.tensor([[0, 1, 2],
                               [1, 0, 0]], dtype=torch.long)
    x = torch.randn(3, 10)
    y = torch.tensor([1]).long()

    data = Data(x=x, y=y, edge_index=edge_index)


    # data_list = [data, data, data, data] #right
    data_list = [data, data, data] #error

    from torch_geometric.loader import DataLoader
    loader = DataLoader(data_list, batch_size=2)

    for batch in loader:
        z = model(batch.cuda())
 
        print(z.shape)
```
The program executes normally when the element in the batch is exactly equal to the batchsize, but an error occurs if the element is smaller than the batchsize.

Exception has occurred: RuntimeError
CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
  File "C:\DevelopFolder\1_GAE_transformer_CNN\7_UCIHAR\models\gae_transformer copy.py", line 23, in forward
    x = self.conv1(x, edge_index).relu()
  File "C:\DevelopFolder\1_GAE_transformer_CNN\7_UCIHAR\models\gae_transformer copy.py", line 45, in <module>
    z = model(batch.cuda())
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

### Environment

* PyG version:2.2.0
* PyTorch version:1.13.0
* OS: win10
* Python version:
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda and pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): 2.1.0+pt113cu116

**Comment by EdisonLeeeee** [comment]
You may need to set `cached=False` in `GCNConv` since the graphs in each batch are different.

**Comment by finquick** [comment]
> 

Oh yes, this problem was solved by setting up dataloader. Thank you very much!
